#!/usr/bin/env bash

function toggleDND () {
    feedback="org.sigxcpu.feedbackd profile"
    getFeedback=$(gsettings get $feedback)

    if ! [ "$1" = "$(echo "${getFeedback//\'}")" ]; then
        gsettings set $feedback "$1"
        amixer sset Master "$2"
        notify-send "Do Not Disturb" "$3"
    fi
}

aplay "$HOME/Music/startup.wav" &> /dev/null &

# Enable cellular if it is disabled
(
    while :
    do
        if mmcli -m 0 | grep "disabled"; then
            mmcli -m 0 -r
        fi

        sleep 60
    done
) &

# TODO: Check for wifi signal and set cellular to 2G, mobile data off
# (
# while :
# do
#
# done
# )

# Toggle DnD
(
    while :
    do
        now=$(date "+%H%M" | awk '$0*=1')

        if (( $now > 1730 )); then
            toggleDND "full" "100%" "Disabled"
        elif (( $now > 930 )); then
            toggleDND "silent" "0%" "Enabled"
        elif (( $now > 850 )); then
            toggleDND "full" "100%" "Disabled"
        elif (( $now > 50 )); then
            toggleDND "silent" "0%" "Enabled"
        fi

        sleep 60
    done
) &
